name: deploy on merge
on:
  pull_request: [close]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved by ${{ github.actor }}"
      - uses: actions/checkout@v1
      - run: echo "git status"    
      - run: echo "git checkout main"
      - run: echo "git pull origin main"
