name: Merge - Deploy - Delete

on:
  pull_request_review:
    types: [submitted]
    branches: 
      - 'main'

jobs:
  mergepal-merge: 

    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
      - run: echo "GITHUB_ACTOR ${{ github.actor }}"
      - run: echo "GITHUB_HEAD_REF ${{ github.head_ref }}"
      - run: echo "GITHUB_REF ${{github.ref}}"
      
#       - uses: actions/checkout@v1
#       - uses: maxkomarychev/merge-pal-action@v0.5.1
#         with:
#           token: ${{ secrets.GIT_TOKEN }}
#       - run: echo "This PR MERGED"
