name: Merge PR when approved and Delete Branch

on:
  pull_request_review:
    types: [submitted]

jobs:
  mergepal-merge: 
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' && github.actor == 'jaireina'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
      - run: echo "GITHUB_ACTOR ${{ github.actor }}"
      - run: echo "github.event.pull_request.base.ref ${{github.event.pull_request.base.ref }}"
      
#       - uses: actions/checkout@v1
#       - uses: maxkomarychev/merge-pal-action@v0.5.1
#         with:
#           token: ${{ secrets.GIT_TOKEN }}
#       - run: echo "This PR MERGED"
