name: Merge PR when approved and Delete Branch

on:
  pull_request_review:
    types: [submitted]

jobs:
  merge-branch: 
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' && github.actor == 'jaireina'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved by ${{ github.actor }}"
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@v0.5.1
        with:
          token: ${{ secrets.GIT_TOKEN }}
          
  delete-branch:
    needs: merge-branch
    runs-on: ubuntu-latest
    steps: 
      - uses: AnandChowdhary/delete-merged-action@v1.2.4
        with:
          branches: '${{ github.event.pull_request.head.ref }}'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
